/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Thu Mar 19 16:04:56 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


